version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/temp:/app/temp
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: next-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
